import { HoleScore } from './hole-score';

export const HOLESCORES: HoleScore[] = [
  { roundid: 1, holeid: 1, playerid: 1, strokes: 4, putts: 2},
  { roundid: 1, holeid: 2, playerid: 1, strokes: 5, putts: 2},
  { roundid: 1, holeid: 3, playerid: 1, strokes: 4, putts: 2},
  { roundid: 1, holeid: 4, playerid: 1, strokes: 3, putts: 2},
  { roundid: 1, holeid: 5, playerid: 1, strokes: 4, putts: 2},
  { roundid: 1, holeid: 6, playerid: 1, strokes: 4, putts: 2},
  { roundid: 1, holeid: 7, playerid: 1, strokes: 5, putts: 2},
  { roundid: 1, holeid: 8, playerid: 1, strokes: 3, putts: 2},
  { roundid: 1, holeid: 9, playerid: 1, strokes: 4, putts: 2},

  { roundid: 2, holeid: 10, playerid: 1, strokes: 5, putts: 2},
  { roundid: 2, holeid: 11, playerid: 1, strokes: 6, putts: 2},
  { roundid: 2, holeid: 12, playerid: 1, strokes: 3, putts: 2},
  { roundid: 2, holeid: 13, playerid: 1, strokes: 4, putts: 2},
  { roundid: 2, holeid: 14, playerid: 1, strokes: 5, putts: 2},
  { roundid: 2, holeid: 15, playerid: 1, strokes: 6, putts: 2},
  { roundid: 2, holeid: 16, playerid: 1, strokes: 3, putts: 2},
  { roundid: 2, holeid: 17, playerid: 1, strokes: 4, putts: 2},
  { roundid: 2, holeid: 18, playerid: 1, strokes: 5, putts: 2},

  { roundid: 3, holeid: 1, playerid: 3, strokes: 5, putts: 2},
  { roundid: 3, holeid: 2, playerid: 3, strokes: 4, putts: 2},
  { roundid: 3, holeid: 3, playerid: 3, strokes: 3, putts: 2},
  { roundid: 3, holeid: 4, playerid: 3, strokes: 6, putts: 2},
  { roundid: 3, holeid: 5, playerid: 3, strokes: 4, putts: 2},
  { roundid: 3, holeid: 6, playerid: 3, strokes: 4, putts: 2},
  { roundid: 3, holeid: 7, playerid: 3, strokes: 6, putts: 2},
  { roundid: 3, holeid: 8, playerid: 3, strokes: 4, putts: 2},
  { roundid: 3, holeid: 9, playerid: 3, strokes: 3, putts: 2},

  { roundid: 4, holeid: 10, playerid: 3, strokes: 6, putts: 2},
  { roundid: 4, holeid: 11, playerid: 3, strokes: 5, putts: 2},
  { roundid: 4, holeid: 12, playerid: 3, strokes: 6, putts: 2},
  { roundid: 4, holeid: 13, playerid: 3, strokes: 3, putts: 2},
  { roundid: 4, holeid: 14, playerid: 3, strokes: 4, putts: 2},
  { roundid: 4, holeid: 15, playerid: 3, strokes: 4, putts: 2},
  { roundid: 4, holeid: 16, playerid: 3, strokes: 6, putts: 2},
  { roundid: 4, holeid: 17, playerid: 3, strokes: 3, putts: 2},
  { roundid: 4, holeid: 18, playerid: 3, strokes: 4, putts: 2},

  { roundid: 5, holeid: 1, playerid: 2, strokes: 6, putts: 2},
  { roundid: 5, holeid: 2, playerid: 2, strokes: 6, putts: 2},
  { roundid: 5, holeid: 3, playerid: 2, strokes: 3, putts: 2},
  { roundid: 5, holeid: 4, playerid: 2, strokes: 4, putts: 2},
  { roundid: 5, holeid: 5, playerid: 2, strokes: 5, putts: 2},
  { roundid: 5, holeid: 6, playerid: 2, strokes: 5, putts: 2},
  { roundid: 5, holeid: 7, playerid: 2, strokes: 6, putts: 2},
  { roundid: 5, holeid: 8, playerid: 2, strokes: 3, putts: 2},
  { roundid: 5, holeid: 9, playerid: 2, strokes: 3, putts: 2},

  { roundid: 6, holeid: 10, playerid: 2, strokes: 3, putts: 2},
  { roundid: 6, holeid: 11, playerid: 2, strokes: 4, putts: 2},
  { roundid: 6, holeid: 12, playerid: 2, strokes: 3, putts: 2},
  { roundid: 6, holeid: 13, playerid: 2, strokes: 4, putts: 2},
  { roundid: 6, holeid: 14, playerid: 2, strokes: 3, putts: 2},
  { roundid: 6, holeid: 15, playerid: 2, strokes: 4, putts: 2},
  { roundid: 6, holeid: 16, playerid: 2, strokes: 4, putts: 2},
  { roundid: 6, holeid: 17, playerid: 2, strokes: 4, putts: 2},
  { roundid: 6, holeid: 18, playerid: 2, strokes: 5, putts: 2},

  { roundid: 7, holeid: 1, playerid: 4, strokes: 5, putts: 2},
  { roundid: 7, holeid: 2, playerid: 4, strokes: 5, putts: 2},
  { roundid: 7, holeid: 3, playerid: 4, strokes: 5, putts: 2},
  { roundid: 7, holeid: 4, playerid: 4, strokes: 5, putts: 2},
  { roundid: 7, holeid: 5, playerid: 4, strokes: 5, putts: 2},
  { roundid: 7, holeid: 6, playerid: 4, strokes: 5, putts: 2},
  { roundid: 7, holeid: 7, playerid: 4, strokes: 5, putts: 2},
  { roundid: 7, holeid: 8, playerid: 4, strokes: 5, putts: 2},
  { roundid: 7, holeid: 9, playerid: 4, strokes: 5, putts: 2},

  { roundid: 8, holeid: 10, playerid: 4, strokes: 5, putts: 2},
  { roundid: 8, holeid: 11, playerid: 4, strokes: 6, putts: 2},
  { roundid: 8, holeid: 12, playerid: 4, strokes: 4, putts: 2},
  { roundid: 8, holeid: 13, playerid: 4, strokes: 4, putts: 2},
  { roundid: 8, holeid: 14, playerid: 4, strokes: 4, putts: 2},
  { roundid: 8, holeid: 15, playerid: 4, strokes: 4, putts: 2},
  { roundid: 8, holeid: 16, playerid: 4, strokes: 4, putts: 2},
  { roundid: 8, holeid: 17, playerid: 4, strokes: 4, putts: 2},
  { roundid: 8, holeid: 18, playerid: 4, strokes: 4, putts: 2}
];

