import { HoleScore } from './hole-score';

export const HOLESCORES: HoleScore[] = [
  { roundid: 11, holeid: 1, playerid: 1, strokes: 4, putts: 2},
  { roundid: 11, holeid: 2, playerid: 1, strokes: 5, putts: 2},
  { roundid: 11, holeid: 3, playerid: 1, strokes: 4, putts: 2},
  { roundid: 11, holeid: 4, playerid: 1, strokes: 3, putts: 2},
  { roundid: 11, holeid: 5, playerid: 1, strokes: 4, putts: 2},
  { roundid: 11, holeid: 6, playerid: 1, strokes: 4, putts: 2},
  { roundid: 11, holeid: 7, playerid: 1, strokes: 5, putts: 2},
  { roundid: 11, holeid: 8, playerid: 1, strokes: 3, putts: 2},
  { roundid: 11, holeid: 9, playerid: 1, strokes: 4, putts: 2},

  { roundid: 21, holeid: 10, playerid: 1, strokes: 5, putts: 2},
  { roundid: 21, holeid: 11, playerid: 1, strokes: 6, putts: 2},
  { roundid: 21, holeid: 12, playerid: 1, strokes: 3, putts: 2},
  { roundid: 21, holeid: 13, playerid: 1, strokes: 4, putts: 2},
  { roundid: 21, holeid: 14, playerid: 1, strokes: 5, putts: 2},
  { roundid: 21, holeid: 15, playerid: 1, strokes: 6, putts: 2},
  { roundid: 21, holeid: 16, playerid: 1, strokes: 3, putts: 2},
  { roundid: 21, holeid: 17, playerid: 1, strokes: 4, putts: 2},
  { roundid: 21, holeid: 18, playerid: 1, strokes: 5, putts: 2},

  { roundid: 31, holeid: 1, playerid: 3, strokes: 5, putts: 2},
  { roundid: 31, holeid: 2, playerid: 3, strokes: 4, putts: 2},
  { roundid: 31, holeid: 3, playerid: 3, strokes: 3, putts: 2},
  { roundid: 31, holeid: 4, playerid: 3, strokes: 6, putts: 2},
  { roundid: 31, holeid: 5, playerid: 3, strokes: 4, putts: 2},
  { roundid: 31, holeid: 6, playerid: 3, strokes: 4, putts: 2},
  { roundid: 31, holeid: 7, playerid: 3, strokes: 6, putts: 2},
  { roundid: 31, holeid: 8, playerid: 3, strokes: 4, putts: 2},
  { roundid: 31, holeid: 9, playerid: 3, strokes: 3, putts: 2},

  { roundid: 41, holeid: 10, playerid: 3, strokes: 6, putts: 2},
  { roundid: 41, holeid: 11, playerid: 3, strokes: 5, putts: 2},
  { roundid: 41, holeid: 12, playerid: 3, strokes: 6, putts: 2},
  { roundid: 41, holeid: 13, playerid: 3, strokes: 3, putts: 2},
  { roundid: 41, holeid: 14, playerid: 3, strokes: 4, putts: 2},
  { roundid: 41, holeid: 15, playerid: 3, strokes: 4, putts: 2},
  { roundid: 41, holeid: 16, playerid: 3, strokes: 6, putts: 2},
  { roundid: 41, holeid: 17, playerid: 3, strokes: 3, putts: 2},
  { roundid: 41, holeid: 18, playerid: 3, strokes: 4, putts: 2},

  { roundid: 51, holeid: 1, playerid: 2, strokes: 6, putts: 2},
  { roundid: 51, holeid: 2, playerid: 2, strokes: 6, putts: 2},
  { roundid: 51, holeid: 3, playerid: 2, strokes: 3, putts: 2},
  { roundid: 51, holeid: 4, playerid: 2, strokes: 4, putts: 2},
  { roundid: 51, holeid: 5, playerid: 2, strokes: 5, putts: 2},
  { roundid: 51, holeid: 6, playerid: 2, strokes: 5, putts: 2},
  { roundid: 51, holeid: 7, playerid: 2, strokes: 6, putts: 2},
  { roundid: 51, holeid: 8, playerid: 2, strokes: 3, putts: 2},
  { roundid: 51, holeid: 9, playerid: 2, strokes: 3, putts: 2},

  { roundid: 61, holeid: 10, playerid: 2, strokes: 3, putts: 2},
  { roundid: 61, holeid: 11, playerid: 2, strokes: 4, putts: 2},
  { roundid: 61, holeid: 12, playerid: 2, strokes: 3, putts: 2},
  { roundid: 61, holeid: 13, playerid: 2, strokes: 4, putts: 2},
  { roundid: 61, holeid: 14, playerid: 2, strokes: 3, putts: 2},
  { roundid: 61, holeid: 15, playerid: 2, strokes: 4, putts: 2},
  { roundid: 61, holeid: 16, playerid: 2, strokes: 4, putts: 2},
  { roundid: 61, holeid: 17, playerid: 2, strokes: 4, putts: 2},
  { roundid: 61, holeid: 18, playerid: 2, strokes: 5, putts: 2},

  { roundid: 71, holeid: 1, playerid: 4, strokes: 5, putts: 2},
  { roundid: 71, holeid: 2, playerid: 4, strokes: 5, putts: 2},
  { roundid: 71, holeid: 3, playerid: 4, strokes: 5, putts: 2},
  { roundid: 71, holeid: 4, playerid: 4, strokes: 5, putts: 2},
  { roundid: 71, holeid: 5, playerid: 4, strokes: 5, putts: 2},
  { roundid: 71, holeid: 6, playerid: 4, strokes: 5, putts: 2},
  { roundid: 71, holeid: 7, playerid: 4, strokes: 5, putts: 2},
  { roundid: 71, holeid: 8, playerid: 4, strokes: 5, putts: 2},
  { roundid: 71, holeid: 9, playerid: 4, strokes: 5, putts: 2},

  { roundid: 81, holeid: 10, playerid: 4, strokes: 5, putts: 2},
  { roundid: 81, holeid: 11, playerid: 4, strokes: 6, putts: 2},
  { roundid: 81, holeid: 12, playerid: 4, strokes: 4, putts: 2},
  { roundid: 81, holeid: 13, playerid: 4, strokes: 4, putts: 2},
  { roundid: 81, holeid: 14, playerid: 4, strokes: 4, putts: 2},
  { roundid: 81, holeid: 15, playerid: 4, strokes: 4, putts: 2},
  { roundid: 81, holeid: 16, playerid: 4, strokes: 4, putts: 2},
  { roundid: 81, holeid: 17, playerid: 4, strokes: 4, putts: 2},
  { roundid: 81, holeid: 18, playerid: 4, strokes: 4, putts: 2}
];

